### ISSUE TITLE
Kenapa tidak bisa buat yg serba seribu untuk event 4.4?

### ISSUE THREAD

**Issue by kajy66666** [alimsk/bfs#11]
Kenapa tidak bisa buat yg serba seribu untuk event 4.4?
apakah gara2 pake termux androud yg seharusnya pake pc?

**Comment by alimsk** [comment]
ngga ada perbedaan gan, semua di build dari source code yg sama.
bisa jadi produknya yg gk di support botnya, agan baru coba satu produk atau udh banyak produk tapi tetep gabisa?

**Comment by kajy66666** [comment]
Hampir semua mas, sama apakah kalo flashsale mall tidak bisa?
![Uploading Screenshot_20220403-163453286.jpg…]()

**Comment by kajy66666** [comment]
https://shopee.co.id/Gulaku-Sugar-Pouch-2-x-750-gr-i.65323877.4939556439

**Comment by alimsk** [comment]
sekedar info kalo masih ada org yg nyari tau:

bot ini, seperti yg ada di judul dan deskripsinya hanya bisa dipake buat flash sale saja, hanya item yg ada di halaman [flash sale](https://shopee.co.id/flash_sale) saja yg bisa dikerjakan botnya.

jadi gak bisa buat serba seribu dan lain lain.
