### ISSUE TITLE
apakah bisa digunakan untuk shopee malaysia?

### ISSUE THREAD

**Issue by zero9911** [alimsk/bfs#2]
Bisa guna untuk Shopee MY ?

**Comment by alimsk** [comment]
shopee my itu apaan ya

**Comment by joe83** [comment]
> 

shopee malaysia sepertinya

**Comment by zero9911** [comment]
> shopee my itu apaan ya

Ya shopee malaysia

**Comment by alimsk** [comment]
ane gak yakin bakal work, walaupun belum ane coba sendiri tapi mending jangan sih gan, takutnya terdeteksi aktifitas mencurigakan di akun agan, nanti repot kalo udh gitu

**Comment by galangryandana** [comment]
permisi kak, ini bot nya hanya untuk flash sala saja ya? kalau untuk co barang selain flash sale tidak bisa? contohnya co barang serba seribu
