### ISSUE TITLE
bot member baru, hehe

### ISSUE THREAD

**Issue by alimsk** [alimsk/bfs#3]
ada yang punya akun nganggur? syaratnya bisa checkout item via aplikasi android shopee.
mau saya gunakan buat testing member baru.

kalo mau kasih ke saya, nanti saya coba buat dulu bot member baru nya, nah kalo work, baru tak kasih botnya gratis 1 bulan,
ya kalo gak work, apa yang mau saya kasih ke anda.
bot ini gak ane publikasikan ya.
perlu dicatat, kalo kena banned atau apalah, jangan salahin saya, ya karena saya minta akunnya, bukan pinjam.

bisa email saya di alimsk7989@gmail.com

sekian terimakasih, sangat mengontol 😅🙏
![suschips-happychips](https://user-images.githubusercontent.com/51353996/159120382-f89f2c77-366e-493e-984c-f2cb428003cd.gif)

**Comment by joe83** [comment]
Masih butuh akun? Aku email ya?

**Comment by alimsk** [comment]
okeh, issue ini saya close dulu, kalo butuh lagi saya reopen
