### ISSUE TITLE
error saat masukkan cookie (android)

### ISSUE THREAD

**Issue by galangryandana** [alimsk/bfs#4]
error: Get"https://mall.shopee.co.id/api/v2/user/account_info?skip_address=1":
dial tcp: lookup mall.shopee.co.id on [::1]:53: readudp [::1]:44374->[::1]:53: read: connection refused

**Comment by alimsk** [comment]
coba jalanin pake termux-chroot gan
```
pkg install proot resolv-conf
termux-chroot ./bfs
```

**Comment by galangryandana** [comment]
work bang, terimakasih banyakkk

**Comment by daprodyx** [comment]
gan udah pke termux-chroot juga ttp error
