### ISSUE TITLE
error saat login di android

### ISSUE THREAD

**Issue by kajy66666** [alimsk/bfs#5]
Kenapa Cookies selalu error ya? cuma pernah bisa login 1 kali aja, seterusnya cookies selalu error, padahal sudah mengikuti video sama persis.

**Comment by kajy66666** [comment]
error: Get
"https://mall.shopee.co.id/api/v2/user/account_info?ski
p_address=1":
dial tcp: lookup mall.shopee.co.id on [::1]:53: read
udp [::1]:40197->[::1]:53: read: connection refused

**Comment by alimsk** [comment]
#4

**Comment by alimsk** [comment]
belum ada masbro

**Comment by kajy66666** [comment]
ada contacts wa kah mas?
dan kira2 berapa yg premium nya?
