### ISSUE TITLE
Waktu flashsale tidak cocok

### ISSUE THREAD

**Issue by resourcesa** [alimsk/bfs#7]
Gan punya saya tak pasang flashsale pukul 12 mlm tapi kebeli nya kok jam 2.48 ya, padahal stock barang masih banyak
Tp kalo buat beli flashsale yg sudah berlangsung bisa langsung kebeli

**Comment by alimsk** [comment]
bisa kasih link produk?

**Comment by resourcesa** [comment]
https://shopee.co.id/product/138456502/13813886427?smtt=0.274093265-1648342004.9

Saya salah pilih varian makanya stok nya masih banyak

**Comment by resourcesa** [comment]
![Screenshot_20220327_120029](https://user-images.githubusercontent.com/102438892/160267399-f64212ea-3c6e-49ff-9645-a404417ac259.jpg)

Kayak gini gan, flashsale uda mulai tp belum cekout juga

**Comment by alimsk** [comment]
kok beda waktunya ya, yang di termux ama yg di notif
<img src='https://user-images.githubusercontent.com/51353996/160267631-09f3415f-e703-4f91-98a4-4b6bae3c0278.png' width='300'>

**Comment by resourcesa** [comment]
Iya gan, ada cara buat samain tidak, masih belajar soalnya

**Comment by alimsk** [comment]
coba

```
termux-chroot TZ=Asia/Jakarta ./bfs
```

**Comment by alimsk** [comment]
sudah ane fix di versi 1.0.2 gan, dicoba updatenya

**Comment by resourcesa** [comment]
Ok gan, makasih
Saya coba dl

**Comment by alimsk** [comment]
btw yg sekarang menggunakan countdown timer ya, seperti yang terlihat di halaman flash sale shopee:
![](https://user-images.githubusercontent.com/51353996/160335648-02b6cc7f-b7a9-4777-8826-4a559366d58d.png)

**Comment by alimsk** [comment]
btw yg sekarang menggunakan countdown timer, seperti yang terlihat di halaman flash sale shopee:
![](https://user-images.githubusercontent.com/51353996/160335648-02b6cc7f-b7a9-4777-8826-4a559366d58d.png)

**Comment by resourcesa** [comment]
Uda cocok gan waktu nya, makasih
