### ISSUE TITLE
bad address

### ISSUE THREAD

**Issue by Udin08** [alimsk/bfs#8]
![Screenshot_20220331-224119](https://user-images.githubusercontent.com/102754305/161107333-39978a79-9a73-4223-a012-b5a5b8f9b694.png)

**Comment by alimsk** [comment]
coba install dari source gan, step-stepnya:
```
pkg install golang
GOBIN=$HOME go install github.com/alimsk/bfs@main
./bfs
```

**Comment by Samsudin08** [comment]
Makasih bang
